# -*- coding: utf-8 -*-
"""TIRTC_VOIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkNyU7EFyX3NxScL6meS9tJOdP0RkcC3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)
if 'Unnamed: 0' in df.columns:
    df = df.drop(columns=['Unnamed: 0'], errors='ignore')
    print(f"Dataset successfully loaded! Shape: {df.shape}")
display(df.head())

df.info()


display(df.describe())

binary_cols = ['private', 'freepoor', 'freerepat', 'nchronic', 'lchronic']
for col in binary_cols:
    if col in df.columns and df[col].dtype == 'object':
        df[col] = df[col].str.lower().map({'yes': 1, 'no': 0})

plt.figure(figsize=(10, 6))
numeric_df = df.select_dtypes(include=[np.number])
sns.heatmap(numeric_df.corr(), annot=True, cmap='Blues', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix: Factors vs Doctor Visits')
plt.show()

# Compare Doctor Visits by Illness Count
plt.figure(figsize=(9, 5))
sns.boxplot(x='illness', y='visits', data=df)
plt.title('Number of Doctor Visits vs. Reported Illnesses')
plt.xlabel('Number of Illnesses')
plt.ylabel('Doctor Visits')
plt.show()


plt.figure(figsize=(8, 5))
sns.barplot(x='nchronic', y='visits', hue='gender', data=df, palette='Set2')
plt.title('Average Doctor Visits by Chronic Condition and Gender')
plt.xlabel('Chronic Condition (0 = No, 1 = Yes)')
plt.ylabel('Average Visits')
plt.show()

# Check for missing values in each column
print("Missing values per column:")
print(df.isnull().sum())

# Drop or fill missing values if any exist
df = df.dropna()  # Or use df.fillna(method='ffill') depending on your needs